backupSettings:
  autoBackup: false
  fixedMode: false
  # m = minutes, h = hours, d = days; separate each argument with spaces
  lapse: "1d 12h 30m"
  # will be ignored if fixedMode is false
  schedule: "13:00"
  # only accepts days
  deleteOlderThan: "7d"

debug:
  onDebug: false