name: nahum-Inventory-Stuff
version: '${version}'

main: dev.nahum.nahumInventoryStuff.NahumInventoryStuff
api-version: '1.21.11'
load: POSTWORLD

commands:
  echesttools:
    description: Some echest tweaks and tools
    permission: nahum.echesttools
    permission-message: You do not have permission to use this command!
    usage: /<command> <username> (optional)<username>
    aliases: [etools, et]

  inventorytools:
    description: Some inventory tweaks and tools
    permission: nahum.inventorytools
    permission-message: You do not have permission to use this command!
    usage: /<command> <option> <username> (optional)<username>
    aliases: [invtools, itools, invt, it]

  inventoryclear:
    description: Clears the items in the user's inventory or enderchest
    permission: nahum.inventoryclear
    permission-message: You do not have permission to use this command!
    usage: /<command> <option> <username>
    aliases: [invclear, iclear, invc, ic]

  ec:
    description: Some echest tweaks and tools
    permission: nahum.ec
    permission-message: You do not have permission to use this command!
    usage: /<command> <option> <username>
    aliases: [ecc, echest]

  inv:
    description: Some inv tweaks and tools
    permission: nahum.inv
    permission-message: You do not have permission to use this command!
    usage: /<command> <option> <username>
    aliases: [inventory, iv]

  nahumstuff:
    description: NahumInventoryStuff control pannel
    permission: nahum.stuff
    permission-message: You do not have permission to use this command!
    usage: /<command> <option>
    aliases: [nahuminvstuff, nahuminv, nahumis, nahumiv]